### ISSUE TITLE
Request support for AMD

### ISSUE THREAD

**Issue by Ac3sRwild** [ich777/unraid-nvtop#1]
Since AMD gpu's are now supported by nvtop can we perhaps change the check for the Nvidia Driver package to also include the radeon-top package which should provide the necessary drivers?

**Comment by ich777** [comment]
I will look onto that but I think it would be better that the developer from Nvtop splits out the Radeon part into a new application or rename the project entirely because this is a bit missleading.

**Comment by ich777** [comment]
@Ac3sRwild please install/update the plugin and see if it's now working.
I can't test if everything is working for AMD because I have no card on hand.

**Comment by Ac3sRwild** [comment]
Works great on my AMD machine. Thank You!
